// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjRg4j67qxFB0q50lJPi1A8v0RZDScXM8',
    appId: '1:989525129932:web:6a52a4701104303c3da069',
    messagingSenderId: '989525129932',
    projectId: 'creditcardfortress',
    authDomain: 'creditcardfortress.firebaseapp.com',
    storageBucket: 'creditcardfortress.appspot.com',
    measurementId: 'G-3GD2X3XE1W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeT_MyWOFWfLREQk8pH2uoeo-ML-y3K8k',
    appId: '1:989525129932:android:30f2edba8ac849393da069',
    messagingSenderId: '989525129932',
    projectId: 'creditcardfortress',
    storageBucket: 'creditcardfortress.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6SNRGko08HHA8lKciV0NKZjmkmME3iOo',
    appId: '1:989525129932:ios:3d456b4c672824be3da069',
    messagingSenderId: '989525129932',
    projectId: 'creditcardfortress',
    storageBucket: 'creditcardfortress.appspot.com',
    iosBundleId: 'com.example.creditcardFortress',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6SNRGko08HHA8lKciV0NKZjmkmME3iOo',
    appId: '1:989525129932:ios:d565c1421d7f97443da069',
    messagingSenderId: '989525129932',
    projectId: 'creditcardfortress',
    storageBucket: 'creditcardfortress.appspot.com',
    iosBundleId: 'com.example.creditcardFortress.RunnerTests',
  );
}
